"""
Visualization helpers for inspecting toy network scenarios.

Two main plots:
  - plot_cluster_traffic_matrix: heatmap of aggregate traffic between clusters
  - plot_link_traffic: network diagram with edge widths scaled by traffic volume

Generated by Claude AI
"""

import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.colors as mcolors
import networkx as nx
import numpy as np


def _cluster_of(node: str) -> str:
    return node.split('_')[0]


def _sorted_clusters(graph: nx.DiGraph) -> list[str]:
    return sorted(set(_cluster_of(n) for n in graph.nodes))


def _aggregate_cluster_traffic(graph: nx.DiGraph, traffic_matrix: dict) -> tuple[list[str], np.ndarray]:
    """Return (cluster_names, matrix) where matrix[i,j] is total source->dest traffic."""
    clusters = _sorted_clusters(graph)
    idx = {c: i for i, c in enumerate(clusters)}
    matrix = np.zeros((len(clusters), len(clusters)))
    for source in graph.nodes:
        for dest in graph.nodes:
            if source == dest:
                continue
            i = idx[_cluster_of(source)]
            j = idx[_cluster_of(dest)]
            matrix[i, j] += traffic_matrix[source][dest]
    return clusters, matrix


def _compute_link_traffic(graph: nx.DiGraph, routes: list, traffic_matrix: dict) -> dict:
    """Return a dict mapping each directed edge (u, v) to total traffic volume through it."""
    link_traffic = {edge: 0. for edge in graph.edges}
    for route in routes:
        source, dest = route[0], route[-1]
        volume = traffic_matrix[source][dest]
        for u, v in zip(route, route[1:]):
            link_traffic[(u, v)] = link_traffic.get((u, v), 0.) + volume
    return link_traffic


def plot_cluster_traffic_matrix(
    graph: nx.DiGraph,
    traffic_matrix: dict,
    ax: plt.Axes = None,
    title: str = None,
) -> plt.Axes:
    """
    Heatmap of aggregate traffic between clusters.

    Rows are source clusters, columns are destination clusters.
    Cell values are the sum of traffic_matrix[s][d] over all node pairs (s, d)
    in that cluster pair (excluding same-node pairs).
    """
    if ax is None:
        _, ax = plt.subplots(figsize=(5, 4))

    clusters, matrix = _aggregate_cluster_traffic(graph, traffic_matrix)
    n = len(clusters)

    im = ax.imshow(matrix, cmap='YlOrRd', aspect='auto')

    ax.set_xticks(range(n))
    ax.set_yticks(range(n))
    ax.set_xticklabels(clusters)
    ax.set_yticklabels(clusters)
    ax.set_xlabel('Destination cluster')
    ax.set_ylabel('Source cluster')

    # Annotate each cell with its value
    vmax = matrix.max()
    for i in range(n):
        for j in range(n):
            val = matrix[i, j]
            # Use white text on dark cells, black on light cells
            text_color = 'white' if val > 0.6 * vmax else 'black'
            ax.text(j, i, f'{val:.1f}', ha='center', va='center',
                    fontsize=8, color=text_color)

    plt.colorbar(im, ax=ax, label='Total traffic')

    if title:
        ax.set_title(title)

    return ax


def plot_link_traffic(
    graph: nx.DiGraph,
    routes: list,
    traffic_matrix: dict,
    ax: plt.Axes = None,
    title: str = None,
    max_edge_width: float = 6.0,
    node_size: int = 120,
) -> plt.Axes:
    """
    Network diagram with edge widths proportional to traffic volume.

    Nodes are colored by cluster. Each directed edge pair (u->v and v->u)
    is drawn as a curved arc so both directions are visible. Node labels
    show only the index within the cluster to reduce clutter.
    """
    if ax is None:
        _, ax = plt.subplots(figsize=(6, 5))

    link_traffic = _compute_link_traffic(graph, routes, traffic_matrix)
    pos = {node: (graph.nodes[node]['x'], graph.nodes[node]['y']) for node in graph.nodes}

    # Assign a color to each cluster
    clusters = _sorted_clusters(graph)
    palette = cm.tab10(np.linspace(0, 0.9, len(clusters)))
    cluster_color = {c: palette[i] for i, c in enumerate(clusters)}
    node_colors = [cluster_color[_cluster_of(n)] for n in graph.nodes]

    # Draw nodes
    nx.draw_networkx_nodes(graph, pos, node_color=node_colors,
                           node_size=node_size, ax=ax)
    nx.draw_networkx_labels(graph, pos,
                            labels={n: n.split('_')[1] for n in graph.nodes},
                            font_size=6, ax=ax)

    # Draw edges scaled by traffic; use curved arcs for directed pairs
    max_traffic = max((v for v in link_traffic.values()), default=1.)
    if max_traffic == 0:
        max_traffic = 1.

    norm = mcolors.Normalize(vmin=0, vmax=max_traffic)
    cmap = cm.Blues

    for (u, v), traffic in link_traffic.items():
        width = max_edge_width * traffic / max_traffic
        color = cmap(norm(traffic))
        nx.draw_networkx_edges(
            graph, pos,
            edgelist=[(u, v)],
            width=width,
            edge_color=[color],
            connectionstyle='arc3,rad=0.15',
            arrows=True,
            arrowsize=8,
            ax=ax,
        )

    # Legend for clusters
    handles = [
        plt.Line2D([0], [0], marker='o', color='w',
                   markerfacecolor=cluster_color[c], markersize=8, label=c)
        for c in clusters
    ]
    ax.legend(handles=handles, loc='best', fontsize=8)

    ax.set_aspect('equal')
    ax.axis('off')

    if title:
        ax.set_title(title)

    return ax


def plot_scenario(
    graph: nx.DiGraph,
    routes: list,
    traffic_initial: dict,
    traffic_final: dict,
    scenario_name: str = '',
):
    """
    Show a 2x2 grid: cluster traffic matrices and link traffic plots
    for both initial (alpha=0) and final (alpha=1) traffic states.
    """
    fig, axes = plt.subplots(2, 2, figsize=(12, 10))
    fig.suptitle(scenario_name, fontsize=14)

    plot_cluster_traffic_matrix(graph, traffic_initial,
                                ax=axes[0, 0], title='Cluster traffic (initial)')
    plot_cluster_traffic_matrix(graph, traffic_final,
                                ax=axes[0, 1], title='Cluster traffic (final)')
    plot_link_traffic(graph, routes, traffic_initial,
                      ax=axes[1, 0], title='Link traffic (initial)')
    plot_link_traffic(graph, routes, traffic_final,
                      ax=axes[1, 1], title='Link traffic (final)')

    fig.tight_layout()
    return fig
